version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
  AfterInstall:
    - location: scripts/after_deploy.sh