version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/diary-server
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      runas: root
  AfterInstall:
    - location: scripts/after_deploy.sh
      runas: root