version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
  db:
    image: postgres:14.1
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command:
      - —character-set-server=utf8mb4
      - —collation-server=utf8mb4_unicode_ci
    ports:
      - "5432:5432"